# Setting up verbosity
/tracking/verbose 0
/run/verbose 0
#
# Setting up the source
#
/run/initilize
/control/execute macros/neutronSource.mac
#
# Setting up the analysis
#
/analysis/setFileName GS20_Neutron_Birks 
/analysis/h1/set 1 100 0  10000 none    # Number of Optical Photons
# Running through absorber thickness
/run/beamOn 100
/analysis/setFileName GS20_Neutron_Birks_1
/analysis/h1/set 1 100 0  10000 none    # Number of Optical Photons
/det/setBirks 0.001
/det/update
/run/beamOn 100
#
/analysis/setFileName GS20_Neutron_Birks_2
/analysis/h1/set 1 100 0  10000 none    # Number of Optical Photons
/det/setBirks 0.01
/det/update
/run/beamOn 100
#
/analysis/setFileName GS20_Neutron_Birks_3
/analysis/h1/set 1 100 0  10000 none    # Number of Optical Photons
/det/setBirks 0.1
/det/update
/run/beamOn 100

