# Setting up verbosity
/tracking/verbose 0
/run/verbose 0
# 
# Running the co60 beam source
#
/control/execute macros/co60Source.mac
#
# PS LiF Simulation 
#
/det/setDetectorMaterial PSLiF
/det/setDetectorThick 50 um
/det/setDetectorRadius 2 cm
/det/update
/analysis/setFileName PS_Neutron 
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h1/set 2 100 0  6000 none    # Number of Optical Photons
/analysis/h1/set 3 100 0  6000 none    # Number of Optical Photons
/run/beamOn 1000000
#
# GS20 Simulation
#
/det/setDetectorMaterial GS20
/det/setDetectorThick  2 mm
/det/setDetectorRadius 1.27 cm
/det/update
/analysis/setFileName GS20_Neutron 
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h1/set 2 100 0  6000 none    # Number of Optical Photons
/analysis/h1/set 3 100 0  6000 none    # Number of Optical Photons
