# Setting up verbosity
/tracking/verbose 0
/run/verbose 0
#
# Setting up the analysis
#
/Analysis/setParticleName neutron
/Analysis/setHistogramMax 5.0 MeV
#
# Setting up the source
#
/control/execute macros/neutronSource.mac
#
# Setting up the detector
#
/PolymerTransport/det/setAbsMat PS_Detector
/PolymerTransport/det/setGapMat G4_PLEXIGLASS
/PolymerTransport/det/setGapThick 1 cm
/PolymerTransport/det/setRadius 10 cm
#
# Running through absorber thickness
/PolymerTransport/det/setAbsThick 2.5 cm
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000
#
/PolymerTransport/det/setAbsThick 1.0 cm
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000

/PolymerTransport/det/setAbsThick 2.5 mm
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000
#
/PolymerTransport/det/setAbsThick 1.0 mm
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000
#
/PolymerTransport/det/setAbsThick 0.5 mm
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000
#
/PolymerTransport/det/setAbsThick 0.25 mm
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000
#
/PolymerTransport/det/setAbsThick 0.1 mm
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000
#
/PolymerTransport/det/setAbsThick 50 um
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000
#
/PolymerTransport/det/setAbsThick 25 um
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000
#
/PolymerTransport/det/setAbsThick 10 um
/Analysis/setEDepPosAnalysis 1
/PolymerTransport/det/update
/run/beamOn 1000000
