/det/setSize 10 um
/run/beamOn 10000
/det/setSize 22 um
/run/beamOn 10000
/det/setSize 46 um
/run/beamOn 10000
/det/setSize 100 um
/run/beamOn 10000
/det/setSize 220 um
/run/beamOn 10000
/det/setSize 460 um
/run/beamOn 10000
/det/setSize 1 mm
/run/beamOn 10000
/det/setSize 2.2 mm
/run/beamOn 10000
/det/setSize 4.6 mm
/run/beamOn 10000
/det/setSize 10 mm
/run/beamOn 10000
/det/setSize 22 mm
/run/beamOn 10000
/det/setSize 46 mm
/run/beamOn 10000
