#
# Macro file for "rangeSim.cc"
# 
# compute the csda range of primary particle
#
/control/verbose 0
/run/verbose 0
#
/det/setMat G4_POLYSTYRENE 
#
/run/initialize
#
# Simulated Ranges
/gun/particle e-
/gun/energy 5 keV
/run/beamOn 100000
#
/gun/energy 10 keV
/run/beamOn 100000
#
/gun/energy 50 keV
/run/beamOn 100000
#
/gun/energy 100 keV
/run/beamOn 100000
#
/gun/energy 500 keV
/run/beamOn 100000
#
