# Setting up verbosity
/tracking/verbose 0
/run/verbose 0
#
# Setting up the analysis
#
#
# Setting up the source
#
/control/execute macros/neutronSource.mac
#
# Setting up the detector
#
/PolymerTransport/det/setAbsMat PS_Detector
/PolymerTransport/det/setGapMat G4_PLEXIGLASS
/PolymerTransport/det/setGapThick 1 cm
/PolymerTransport/det/setRadius 10 cm
#
#
# Running through absorber thickness
#
/analysis/setFileName neutron_25mm
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 2.5 cm none # Position Histogram 
/PolymerTransport/det/setAbsThick 2.5 cm
/PolymerTransport/det/update
/run/beamOn 1000000
#
/analysis/setFileName neutron_10mm
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 1.0 cm none # Position Histogram 
/PolymerTransport/det/setAbsThick 1.0 cm
/PolymerTransport/det/update
/run/beamOn 1000000
#
/analysis/setFileName neutron_2500um
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 2.5 mm none # Position Histogram 
/PolymerTransport/det/setAbsThick 2.5 mm
/PolymerTransport/det/update
/run/beamOn 1000000
#
/analysis/setFileName neutron_1000mm
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 1.0 mm none # Position Histogram 
/PolymerTransport/det/setAbsThick 1.0 mm
/PolymerTransport/det/update
/run/beamOn 1000000
#
/analysis/setFileName neutron_500um
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 0.5 mm none # Position Histogram 
/PolymerTransport/det/setAbsThick 0.5 mm
/PolymerTransport/det/update
/run/beamOn 1000000
#
/analysis/setFileName neutron_250um
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 0.25 mm none # Position Histogram 
/PolymerTransport/det/setAbsThick 0.25 mm
/PolymerTransport/det/update
/run/beamOn 1000000
#
/analysis/setFileName neutron_100um
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 0.1 mm none # Position Histogram 
/PolymerTransport/det/setAbsThick 0.1 mm
/PolymerTransport/det/update
/run/beamOn 1000000
#
/analysis/setFileName neutron_50um
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 50 um none # Position Histogram 
/PolymerTransport/det/setAbsThick 50 um
/PolymerTransport/det/update
/run/beamOn 1000000
#
/analysis/setFileName neutron_25um
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 25 um none # Position Histogram 
/PolymerTransport/det/setAbsThick 25 um
/PolymerTransport/det/update
/run/beamOn 1000000
#
/analysis/setFileName neutron_10um
/analysis/h1/set 1 100 0  5.0 MeV none # Energy Depostion
/analysis/h2/set 1 100 0 5.0 MeV none 100 0 10 um none # Position Histogram 
/PolymerTransport/det/setAbsThick 10 um
/PolymerTransport/det/update
/run/beamOn 1000000
