# 1D neutron beam incident upon a surface of radius 3 mm in the y-z plane
# at the origin.  Beam is traveling along the x-axis
/gps/particle neutron
/gps/pos/type Beam
#
# the incident surface is in the x-y plane
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
#
# the beam spot is centered at the origin and is 
# of 1d gaussian shape with a 3mm central plateau
/gps/pos/shape Circle 
/gps/pos/centre 0. 0. 10 cm
/gps/pos/radius 3. mm
#
# the beam is travelling along the z-axis with 5 degrees dispersion
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 1 0
/gps/ang/sigma_r 0. deg
#  
# the beam energy is mono energic
/gps/ene/type Mono
/gps/ene/mono 0.025 eV

